# Generated by Django 4.2.7 on 2023-12-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isGroupChat',
            field=models.BooleanField(default=False),
        ),
    ]
