# Generated by Django 4.2.7 on 2023-12-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_isgroupchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(blank=True, upload_to='profile_pic/'),
        ),
    ]
